/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Class.Report.ProductoReporte;
import Class.Report.ProveedorReporte;
import Controller.*;
import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.CellStyle;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author manuel
 */
public class frmReporteProveedores extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteProveedores
     */
    ProveedorControlador ctlProveedor;
    ProductoControlador ctlProducto;

    public frmReporteProveedores() {
        this.ctlProveedor = new ProveedorControlador();
        this.ctlProducto = new ProductoControlador();
        initComponents();

        this.generarReporte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlReporteProveedor = new javax.swing.JPanel();
        btnGenerarExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("ReporteProveedores");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReporteProveedorLayout = new javax.swing.GroupLayout(pnlReporteProveedor);
        pnlReporteProveedor.setLayout(pnlReporteProveedorLayout);
        pnlReporteProveedorLayout.setHorizontalGroup(
            pnlReporteProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlReporteProveedorLayout.setVerticalGroup(
            pnlReporteProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        btnGenerarExcel.setText("Generar Excel");
        btnGenerarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(54, 54, 54)))
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarExcel))
                    .addComponent(pnlReporteProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarExcel)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReporteProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        frmProveedores menuProveedor = new frmProveedores();
//        menuProveedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGenerarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarExcelActionPerformed
        try {
            ArrayList<ProductoReporte> listaProductos;
            listaProductos = this.ctlProducto.obtenerLista();
            if (listaProductos == null) {
                return;
            }

            HSSFWorkbook book = new HSSFWorkbook();
            HSSFSheet sheet = book.createSheet();
            book.setSheetName(0, "Listado de productos");

            String[] headers = new String[]{
                "Nombre",
                "Precio actual",
                "Proveedor",
                "NIT proveedor",
                "Existencia"
            };

            CellStyle headerCellStyle = book.createCellStyle();
            HSSFFont font = book.createFont();
            font.setBold(true);
            headerCellStyle.setFont(font);

            HSSFRow headersRow = sheet.createRow(0);
            for (int i = 0; i < headers.length; i++) {
                String header = headers[i];
                HSSFCell cell = headersRow.createCell(i);
                cell.setCellStyle(headerCellStyle);
                cell.setCellValue(header);
            }

            for (int i = 0; i < listaProductos.size(); i++) {
                HSSFRow row = sheet.createRow(i + 1);
                row.createCell(0).setCellValue(listaProductos.get(i).getNombre());
                row.createCell(1).setCellValue(listaProductos.get(i).getPrecio_actual());
                row.createCell(2).setCellValue(listaProductos.get(i).getProveedor());
                row.createCell(3).setCellValue(listaProductos.get(i).getNit() + "");
                row.createCell(4).setCellValue(listaProductos.get(i).getExistencia());
            }
            try {
                FileOutputStream file = new FileOutputStream("listado_productos.xls");
                book.write(file);
                file.close();

            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {

            }
        } catch (SQLException e) {

        }
    }//GEN-LAST:event_btnGenerarExcelActionPerformed

    public void generarReporte() {
        ArrayList<ProveedorReporte> listReport = new ArrayList<>();
        try {
            listReport = this.ctlProveedor.obtenerReporte();

            if (listReport == null) {
                JOptionPane.showMessageDialog(this, "No hay datos para generar el reporte", "Gestion de proveedores", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // configurar grafico
            DefaultPieDataset dataset = new DefaultPieDataset();

            for (ProveedorReporte temp : listReport) {
                dataset.setValue(temp.getRazon_social(), temp.getCantidad());
            }

            JFreeChart chart = ChartFactory.createPieChart("Productos por proveedor", dataset, true, true, false);
            ChartPanel panel = new ChartPanel(chart);
            panel.setMouseWheelEnabled(true);

            this.pnlReporteProveedor.setLayout(new java.awt.BorderLayout());
            this.pnlReporteProveedor.add(panel, BorderLayout.CENTER);
            this.pnlReporteProveedor.validate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos", "Gestion de proveedores", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteProveedores().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarExcel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlReporteProveedor;
    // End of variables declaration//GEN-END:variables
}
